DROP DATABASE SELF;
CREATE DATABASE SELF;
USE SELF;

CREATE TABLE DEPTO(
E_NAME VARCHAR(10),
E_ID INT,
S_ID INT,
PRIMARY KEY (E_ID),
FOREIGN KEY (S_ID) references DEPTO(E_ID)
);

INSERT INTO DEPTO VALUES('DANIEL',1,1);
INSERT INTO DEPTO VALUES('ANNA',2,1);
INSERT INTO DEPTO VALUES('HENRIQUE',3,1);
INSERT INTO DEPTO VALUES('LUCIA',4,3);
INSERT INTO DEPTO VALUES('ADRIANA',5,3);

CREATE TABLE EMPRESA(
E_NAME VARCHAR(10),
E_ID INT,
E_DEPT VARCHAR(10),
E_LOC VARCHAR(10)
);
INSERT INTO EMPRESA VALUES('DANIEL',1,'RH','SP');
INSERT INTO EMPRESA VALUES('DANIEL',1,'VENDAS','SP');
INSERT INTO EMPRESA VALUES('ANNA',2,'TI','RJ');
INSERT INTO EMPRESA VALUES('ANNA',2,'MARKETING','SP');
INSERT INTO EMPRESA VALUES('HENRIQUE',3,'FINANCAS','RS');
INSERT INTO EMPRESA VALUES('HENRIQUE',3,'FINANCAS','RS');

