// Criando artistas
CREATE (a1:Artista {nome: "Robert De Niro", altura: 177, local_nascto: "New York, USA"})
CREATE (a2:Artista {nome: "Al Pacino", altura: 170, local_nascto: "New York, USA"})
CREATE (a3:Artista {nome: "Fernanda Montenegro", altura: 160, local_nascto: "Rio de Janeiro, Brazil"})
CREATE (a4:Artista {nome: "Leonardo DiCaprio", altura: 183, local_nascto: "Los Angeles, USA"})
CREATE (a5:Artista {nome: "Meryl Streep", altura: 164, local_nascto: "Summit, USA"})
CREATE (a6:Artista {nome: "Scarlett Johansson", altura: 160, local_nascto: "New York, USA"})
CREATE (a7:Artista {nome: "Brad Pitt", altura: 180, local_nascto: "Shawnee, USA"})
CREATE (a8:Artista {nome: "Johnny Depp", altura: 178, local_nascto: "Owensboro, USA"})
CREATE (a9:Artista {nome: "Joaquin Phoenix", altura: 180, local_nascto: "San Juan, Puerto Rico"})
CREATE (a10:Artista {nome: "Tom Hanks", altura: 183, local_nascto: "Concord, USA"})
CREATE (a11:Artista {nome: "Clint Eastwood", altura: 185, local_nascto: "San Francisco, USA"})
CREATE (a12:Artista {nome: "Emma Stone", altura: 168, local_nascto: "Scottsdale, USA"})
CREATE (a13:Artista {nome: "Daniel Craig", altura: 178, local_nascto: "Chester, England"})
CREATE (a14:Artista {nome: "Viola Davis", altura: 160, local_nascto: "St. Matthews, USA"})
CREATE (a15:Artista {nome: "Idris Elba", altura: 189, local_nascto: "London, England"})
CREATE (a16:Artista {nome: "Hugh Jackman", altura: 188, local_nascto: "Sydney, Australia"})
CREATE (a17:Artista {nome: "Kate Winslet", altura: 169, local_nascto: "Reading, England"})
CREATE (a18:Artista {nome: "Natalie Portman", altura: 160, local_nascto: "Jerusalem, Israel"})

// Criando filmes
CREATE (f1:Filme {titulo_original: "The Godfather", ano_lancamento: 1972, generos: "Crime, Drama", duracao: 175})
CREATE (f2:Filme {titulo_original: "Heat", ano_lancamento: 1995, generos: "Crime, Thriller", duracao: 170})
CREATE (f3:Filme {titulo_original: "The Irishman", ano_lancamento: 2019, generos: "Crime, Drama", duracao: 209})
CREATE (f4:Filme {titulo_original: "The Departed", ano_lancamento: 2006, generos: "Crime, Drama, Thriller", duracao: 151})
CREATE (f5:Filme {titulo_original: "Gran Torino", ano_lancamento: 2008, generos: "Drama", duracao: 116})
CREATE (f6:Filme {titulo_original: "The Revenant", ano_lancamento: 2015, generos: "Action, Adventure, Drama", duracao: 156})
CREATE (f7:Filme {titulo_original: "Black Swan", ano_lancamento: 2010, generos: "Drama, Thriller", duracao: 108})
CREATE (f8:Filme {titulo_original: "Les Misérables", ano_lancamento: 2012, generos: "Drama, Musical", duracao: 158})
CREATE (f9:Filme {titulo_original: "Finding Neverland", ano_lancamento: 2004, generos: "Biography, Drama", duracao: 101})
CREATE (f10:Filme {titulo_original: "The Assassination of Jesse James by the Coward Robert Ford", ano_lancamento: 2007, generos: "Biography, Crime, Drama", duracao: 160})

// Criando relacionamentos de elenco
CREATE (a1)-[:Elenco {tipo_participacao: "Actor"}]->(f1)
CREATE (a2)-[:Elenco {tipo_participacao: "Actor"}]->(f1)
CREATE (a1)-[:Elenco {tipo_participacao: "Actor"}]->(f3)
CREATE (a3)-[:Elenco {tipo_participacao: "Actor"}]->(f1)
CREATE (a4)-[:Elenco {tipo_participacao: "Actor"}]->(f6)
CREATE (a5)-[:Elenco {tipo_participacao: "Actor"}]->(f8)
CREATE (a7)-[:Elenco {tipo_participacao: "Actor"}]->(f2)
CREATE (a8)-[:Elenco {tipo_participacao: "Actor"}]->(f2)
CREATE (a9)-[:Elenco {tipo_participacao: "Actor"}]->(f6)
CREATE (a10)-[:Elenco {tipo_participacao: "Actor"}]->(f5)
CREATE (a11)-[:Elenco {tipo_participacao: "Actor"}]->(f5)
CREATE (a12)-[:Elenco {tipo_participacao: "Actor"}]->(f7)
CREATE (a13)-[:Elenco {tipo_participacao: "Actor"}]->(f9)
CREATE (a14)-[:Elenco {tipo_participação: "Actor"}]->(f10)
CREATE (a15)-[:Elenco {tipo_participacao: "Actor"}]->(f4)
CREATE (a16)-[:Elenco {tipo_participacao: "Actor"}]->(f4)
CREATE (a17)-[:Elenco {tipo_participacao: "Actor"}]->(f8)
CREATE (a18)-[:Elenco {tipo_participacao: "Actor"}]->(f10) 

