CREATE DATABASE dbdep;
SHOW DATABASES;
USE dbdep;

CREATE TABLE DEPARTAMENTO
(idDepto int NOT NULL,
nomeDepto varchar(30) NOT NULL,
PRIMARY KEY(idDepto));

DESCRIBE DEPARTAMENTO;

INSERT INTO DEPARTAMENTO (idDepto , nomeDepto) VALUES 
(10, 'Compras'),
(20, 'Engenharia'),
(40, 'Vendas'),
(55, 'Financeiro');

SELECT * FROM DEPARTAMENTO;

CREATE TABLE FUNCIONARIO
(idFunc int NOT NULL,
nomeFunc varchar(40) NOT NULL,
CPF char(14) NOT NULL UNIQUE,
idDepto int);

DESCRIBE FUNCIONARIO;

ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO
FOREIGN KEY (idDepto) REFERENCES DEPARTAMENTO(idDepto)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

DESCRIBE FUNCIONARIO;

INSERT INTO FUNCIONARIO (idFunc , nomeFunc , CPF , idDepto)
values 
(3456, 'Paulo de Souza Alves', '345.987.123-98',10 ),
(9872, 'Jose da Silva', '987.243.098-01',10 ),
(1890, 'Pedro Rangel de Souza', '112.872.340-81',NULL),
(4680, 'Angela Silva Medeiros', '567.982.045-27',40 );

SELECT * FROM FUNCIONARIO;

DELETE FROM DEPARTAMENTO WHERE idDepto = 10;
-- Erro key constraint

ALTER TABLE FUNCIONARIO
DROP CONSTRAINT FK_FUNCIONARIO;

ALTER TABLE FUNCIONARIO
ADD CONSTRAINT FK_FUNCIONARIO 
FOREIGN KEY (idDepto) REFERENCES DEPARTAMENTO (idDepto) 
ON DELETE SET NULL;

DELETE FROM DEPARTAMENTO WHERE idDepto = 10;

SELECT * FROM FUNCIONARIO;
SELECT * FROM DEPARTAMENTO;

-- Delete all!
DELETE FROM FUNCIONARIO;
DELETE FROM DEPARTAMENTO;

INSERT INTO DEPARTAMENTO(idDepto , nomeDepto) VALUES 
(10, 'Compras'),
(20, 'Engenharia'),
(40, 'Vendas'),
(55, 'Financeiro');

INSERT INTO FUNCIONARIO (idFunc , nomeFunc , CPF , idDepto) VALUES
(3456, 'Paulo de Souza Alves', '345.987.123-98',10 ),
(9872, 'Jose da Silva', '987.243.098-01',10 ),
(1890, 'Pedro Rangel de Souza', '112.872.340-81',NULL),
(4680, 'Angela Silva Medeiros', '567.982.045-27',40 );

ALTER TABLE FUNCIONARIO
DROP CONSTRAINT FK_FUNCIONARIO;

ALTER TABLE FUNCIONARIO
ADD CONSTRAINT FK_FUNCIONARIO 
FOREIGN KEY (idDepto) REFERENCES DEPARTAMENTO (idDepto) 
ON DELETE CASCADE;

DELETE FROM DEPARTAMENTO 
WHERE idDepto = 10;
-- Ok

SELECT * FROM FUNCIONARIO;
SELECT * FROM DEPARTAMENTO;




